### ISSUE TITLE
game crashing

### ISSUE THREAD

**Issue by tacgod** [DevDyna/IronBerry#15]
### Core Section

- [X] I have searched for this issue on this repository
- [X] This bug persist and I need help

### Environment

Singleplayer/Local | NO LAN

### Modpack Version

0.8e

### Description

im having a problem where the game gives me a kubejs error after finishing loading

### Procedure

start up the game, wait for it to finish loading, and that's it

### Additional things

![image_2024-04-08_223151816](https://github.com/DevDyna/IronBerry/assets/126120945/7e24a57b-7662-445e-8256-0e8e8ccf935f)

[22:28:47] [INIT] KubeJS 1902.6.2-build.63; MC 1902 forge
[22:28:47] [INIT] Loaded plugins:
[22:28:47] [INIT] - dev.latvian.mods.kubejs.forge.BuiltinKubeJSForgePlugin
[22:28:47] [INIT] - dev.latvian.mods.kubejs.forge.BuiltinKubeJSForgeClientPlugin
[22:28:47] [INIT] - com.almostreliable.morejs.Plugin
[22:28:47] [INIT] - pie.ilikepiefoo.AdditionsPlugin
[22:28:47] [INIT] - net.mehvahdjukaar.sawmill.integration.KubeJsPlugin
[22:28:47] [INIT] - dev.footer.paxeljs.kjs.Plugin
[22:28:47] [INIT] - com.probejs.ProbeJSPlugin
[22:28:50] [INFO] Loaded script startup_scripts:blocks.js in 0.275 s
[22:28:50] [INFO] Loaded script startup_scripts:create.js in 0.034 s
[22:28:50] [INFO] Loaded script startup_scripts:fluids.js in 0.023 s
[22:28:50] [INFO] gas.js#1: Loaded Java class 'dev.architectury.platform.forge.EventBuses'
[22:28:50] [INFO] gas.js#2: Loaded Java class 'mekanism.common.registration.impl.GasDeferredRegister'
[22:28:50] [INFO] gas.js#22: Loaded Java class 'mekanism.api.chemical.gas.attribute.GasAttributes'
[22:28:50] [INFO] gas.js#24: Loaded Java class 'mekanism.api.math.FloatingLong'
[22:28:50] [INFO] Loaded script startup_scripts:gas.js in 0.105 s
[22:28:50] [INFO] Loaded script startup_scripts:global.js in 0.052 s
[22:28:50] [INFO] Loaded script startup_scripts:items.js in 0.093 s
[22:28:50] [INFO] Loaded script startup_scripts:modify/blocks.js in 0.0 s
[22:28:50] [INFO] Loaded script startup_scripts:modify/items.js in 0.022 s
[22:28:50] [INFO] Loaded script startup_scripts:social/items.js in 0.001 s
[22:28:50] [INFO] tooltips.js#18: Loaded Java class 'net.minecraft.Util'
[22:28:50] [INFO] tooltips.js#31: Loaded Java class 'com.mojang.datafixers.util.Either'
[22:28:50] [INFO] Loaded script startup_scripts:tooltips.js in 0.032 s
[22:28:50] [INFO] Loaded 10/10 KubeJS startup scripts in 2.631 s
[22:28:51] [ERROR] ! Error occurred while handling event 'StartupEvents.registry': java.lang.IllegalArgumentException: Duplicate key 'kubejs:scaffoldingdelta' in registry 'minecraft:item'!
[22:28:51] [ERROR] ! java.lang.IllegalArgumentException: Duplicate key 'kubejs:scaffoldingdelta' in registry 'minecraft:item'!
[22:28:51] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.63/dev.latvian.mods.kubejs.registry.RegistryInfo.addBuilder(RegistryInfo.java:259)
[22:28:51] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.63/dev.latvian.mods.kubejs.registry.RegistryEventJS.create(RegistryEventJS.java:52)
[22:28:51] [ERROR] ! 	at jdk.internal.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
[22:28:51] [ERROR] ! 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:28:51] [ERROR] ! 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[22:28:51] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.MemberBox.invoke(MemberBox.java:160)
[22:28:51] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.NativeJavaMethod.call(NativeJavaMethod.java:463)
[22:28:51] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.Interpreter.interpretLoop(Interpreter.java:987)
[22:28:51] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.Interpreter.interpret(Interpreter.java:370)
[22:28:51] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[22:28:51] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.Context.callSync(Context.java:1308)
[22:28:51] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.Context.doTopCall(Context.java:1325)
[22:28:51] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.InterpretedFunction.call(InterpretedFunction.java:70)
[22:28:51] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.Context.callSync(Context.java:1308)
[22:28:51] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.ArrowFunction.call(ArrowFunction.java:42)
[22:28:51] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.Context.callSync(Context.java:1308)
[22:28:51] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:125)
[22:28:51] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:74)
[22:28:51] [ERROR] ! 	at TRANSFORMER/jdk.proxy4/jdk.proxy4.$Proxy81.onEvent(Unknown Source)
[22:28:51] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.63/dev.latvian.mods.kubejs.event.EventHandlerContainer.handle(EventHandlerContainer.java:39)
[22:28:51] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.63/dev.latvian.mods.kubejs.event.EventHandler.postToHandlers(EventHandler.java:301)
[22:28:51] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.63/dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:263)
[22:28:51] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.63/dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:225)
[22:28:51] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.63/dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:204)
[22:28:51] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.63/dev.latvian.mods.kubejs.KubeJS.<init>(KubeJS.java:164)
[22:28:51] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.63/dev.latvian.mods.kubejs.forge.KubeJSForge.<init>(KubeJSForge.java:37)
[22:28:51] [ERROR] ! 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[22:28:51] [ERROR] ! 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[22:28:51] [ERROR] ! 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[22:28:51] [ERROR] ! 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[22:28:51] [ERROR] ! 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[22:28:51] [ERROR] ! 	at LAYER PLUGIN/javafmllanguage@1.19.2-43.3.7/net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70)
[22:28:51] [ERROR] ! 	at LAYER PLUGIN/fmlcore@1.19.2-43.3.7/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:122)
[22:28:51] [ERROR] ! 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[22:28:51] [ERROR] ! 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[22:28:51] [ERROR] ! 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[22:28:51] [ERROR] ! 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[22:28:51] [ERROR] ! 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[22:28:51] [ERROR] ! 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[22:28:51] [ERROR] ! 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[22:30:04] [INFO] create.js#2: Loaded Java class 'com.simibubi.create.compat.jei.category.MysteriousItemConversionCategory'
[22:30:04] [INFO] create.js#3: Loaded Java class 'com.simibubi.create.compat.jei.ConversionRecipe'

**Comment by DevDyna** [comment]
very strange bug , thanks to have reported it!
i will investigate to find the cause of what happen

**Comment by DevDyna** [comment]
> start up the game, wait for it to finish loading, and that's it
weird due it apparently not replicable , maybe did you have installed other mods/changes some stuff on modpack before launch it?
![image](https://github.com/DevDyna/IronBerry/assets/78147916/f88444b0-d287-4ae6-b775-363086710376)

**Comment by DevDyna** [comment]
Did you updated the modpack on same instance / place right?
I see that there are 10/10 script files loaded when on startup scripts there are only 9 on total 
-> try to reinstall your instance on another profile and try again (probably was caused by other files removed on time)

**Comment by DevDyna** [comment]
i will close for now , if persist send a comment and i will re-open it
